backtest_settings:
  start_date: '2002-01-01'
  end_date: '2024-12-31'
  rebalance_freq: 'M'
  initial_capital: 100.0
  size: 100.0  # Changed to match initial capital for full investment
  size_type: 'value'  # Using value for fixed position size

data:
  file_path: 'pulling_data/backtest_data.csv'
  target_column: 'cad_ig_er_index'

strategies:
  MA:
    ma_window: 10
    entry_threshold: 0.001
  BuyAndHold:
    min_holding_period: 1
  HYTiming:
    ma_window: 5  # Default value, will be optimized
