sprds:
  field: "INDEX_OAS_TSY_BP"
  securities:
    - ticker: "I05510CA Index"
      custom_name: "cad_ig_oas"
    - ticker: "LUACTRUU Index"
      custom_name: "us_ig_oas"
    - ticker: "LF98TRUU Index"
      custom_name: "us_hy_oas"
    - ticker: "LBEATREU Index"
      custom_name: "eur_ig_oas"
    - ticker: "I34227CA Index"
      custom_name: "cad_ig_oas_1-5yr"
    - ticker: "I34228CA Index"
      custom_name: "cad_ig_oas_5-10yr"
    - ticker: "I34229CA Index"
      custom_name: "cad_ig_oas_>10yr"
    - ticker: "I05523CA Index"
      custom_name: "cad_ig_oas_fins"
    - ticker: "I05520CA Index"
      custom_name: "cad_ig_oas_industrials"
    - ticker: "I05517CA Index"
      custom_name: "cad_ig_oas_utility"
    - ticker: "I05515CA Index"
      custom_name: "cad_ig_oas_a"
    - ticker: "I05516CA Index"
      custom_name: "cad_ig_oas_bbb"
    - ticker: "I34069CA Index"
      custom_name: "cad_prov_oas"
    - ticker: "I34334CA Index"
      custom_name: "cad_prov_oas_1-5yr"
    - ticker: "I34335CA Index"
      custom_name: "cad_prov_oas_5-10yr"
    - ticker: "I34336CA Index"
      custom_name: "cad_prov_oas_10yr"
    - ticker: "I05504 Index"
      custom_name: "cad_prov_cmb"
    - ticker: "I05743US Index"
      custom_name: "us_ig_oas_aaa"
    - ticker: "I05744US Index"
      custom_name: "us_ig_oas_aa"
    - ticker: "I05745US Index"
      custom_name: "us_ig_oas_a"
    - ticker: "I05746US Index"
      custom_name: "us_ig_oas_bbb"
    - ticker: "LU13TRUU Index"
      custom_name: "us_ig_oas_1-3yr"
    - ticker: "LU35TRUU Index"
      custom_name: "us_ig_oas_3-5yr"
    - ticker: "I05749US Index"
      custom_name: "us_ig_oas_5-7yr"
    - ticker: "I05750US Index"
      custom_name: "us_ig_oas_7-10yr"
    - ticker: "I05751US Index"
      custom_name: "us_ig_oas_10yr"
    - ticker: "LUAITRUU Index"
      custom_name: "us_ig_oas_industrials"
    - ticker: "LUAUTRUU Index"
      custom_name: "us_ig_oas_uts"
    - ticker: "I00159US Index"
      custom_name: "us_ig_oas_fins"

derv:
  field: "ROLL_ADJUSTED_MID_PRICE"
  securities:
    - ticker: "IBOXUMAE MKIT Curncy"
      custom_name: "cdx_ig"
    - ticker: "IBOXHYSE MKIT Curncy"
      custom_name: "cdx_hy"

er_ytd:
  field: "INDEX_EXCESS_RETURN_YTD"
  securities:
    - ticker: "I05510CA Index"
      custom_name: "cad_ig_oas"
    - ticker: "LUACTRUU Index"
      custom_name: "us_ig_oas"
    - ticker: "LF98TRUU Index"
      custom_name: "us_hy_oas"
    - ticker: "LBEATREU Index"
      custom_name: "eur_ig_oas"
    - ticker: "I34227CA Index"
      custom_name: "cad_ig_oas_1-5yr"
    - ticker: "I34228CA Index"
      custom_name: "cad_ig_oas_5-10yr"
    - ticker: "I34229CA Index"
      custom_name: "cad_ig_oas_>10yr"
    - ticker: "I05523CA Index"
      custom_name: "cad_ig_oas_fins"
    - ticker: "I05520CA Index"
      custom_name: "cad_ig_oas_industrials"
    - ticker: "I05517CA Index"
      custom_name: "cad_ig_oas_utility"
    - ticker: "I05515CA Index"
      custom_name: "cad_ig_oas_a"
    - ticker: "I05516CA Index"
      custom_name: "cad_ig_oas_bbb"
    - ticker: "I34069CA Index"
      custom_name: "cad_prov_oas"
    - ticker: "I34334CA Index"
      custom_name: "cad_prov_oas_1-5yr"
    - ticker: "I34335CA Index"
      custom_name: "cad_prov_oas_5-10yr"
    - ticker: "I34336CA Index"
      custom_name: "cad_prov_oas_10yr"
    - ticker: "I05504 Index"
      custom_name: "cad_prov_cmb"
    - ticker: "I05743US Index"
      custom_name: "us_ig_oas_aaa"
    - ticker: "I05744US Index"
      custom_name: "us_ig_oas_aa"
    - ticker: "I05745US Index"
      custom_name: "us_ig_oas_a"
    - ticker: "I05746US Index"
      custom_name: "us_ig_oas_bbb"
    - ticker: "LU13TRUU Index"
      custom_name: "us_ig_oas_1-3yr"
    - ticker: "LU35TRUU Index"
      custom_name: "us_ig_oas_3-5yr"
    - ticker: "I05749US Index"
      custom_name: "us_ig_oas_5-7yr"
    - ticker: "I05750US Index"
      custom_name: "us_ig_oas_7-10yr"
    - ticker: "I05751US Index"
      custom_name: "us_ig_oas_10yr"
    - ticker: "LUAITRUU Index"
      custom_name: "us_ig_oas_industrials"
    - ticker: "LUAUTRUU Index"
      custom_name: "us_ig_oas_uts"
    - ticker: "I00159US Index"
      custom_name: "us_ig_oas_fins"

# Default settings
settings:
  default_start_date: "2002-01-01"
  default_end_date: ""  # Empty means today
  data_directory: "data"
  log_directory: "logs"
