backtest_settings:
  end_date: '2024-12-31'
  initial_capital: 100.0
  rebalance_freq: M
  size: 100.0
  size_type: value
  start_date: '2002-01-01'
data:
  file_path: pulling_data/backtest_data.csv
  target_column: cad_ig_er_index
strategies:
  BuyAndHold:
    min_holding_period: 1
  ComplexRegime:
    ma_fast: 4
    ma_med: 12
    ma_slow: 25
    min_holding_period: 2
    mom_long: 10
    mom_short: 3
    momentum_weight: 0.6
    signal_threshold: 0.08
    trend_weight: 0.3
    vol_threshold: 0.22
    vol_weight: 0.1
    vol_window: 8
    zscore_window: 45
  MA:
    entry_threshold: 0.001
    ma_window: 10
  TrendRisk:
    max_leverage: 2.0
    min_holding_period: 1
    signal_threshold: 0.2
    vol_target: 0.1
